# Generated by Django 3.0.7 on 2020-06-14 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[(main.models.IngestionType['BREAKFAST'], 'BREAKFAST'), (main.models.IngestionType['DINNER'], 'DINNER'), (main.models.IngestionType['SNACK'], 'SNACK')], max_length=256)),
                ('calories', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_100g', models.IntegerField()),
                ('weight_in_gramms', models.IntegerField()),
                ('fats_per_100g', models.IntegerField()),
                ('proteins_per_100g', models.IntegerField()),
                ('carbohydrates_per_100g', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParamsOfHike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('people', models.IntegerField()),
                ('ingestions', models.ManyToManyField(to='main.Ingestion')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ListOfProducts')),
            ],
        ),
        migrations.AddField(
            model_name='listofproducts',
            name='list_of_products',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='main.Product'),
        ),
        migrations.CreateModel(
            name='DetailedIngestion',
            fields=[
                ('ingestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Ingestion')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dish')),
            ],
            bases=('main.ingestion',),
        ),
    ]
